---
title: "About"
author: "Matt Crump"
---

The purpose of this website is to host online cognition experiments for teaching and research purposes.

We are following in the steps of other "citizen science" projects, with the goal of opening our research process to include our local community, and the online public at large.

We hope that participating in our experiments will be an interesting and educational experience.


## FAQs

### What is this website?

This website shares access to participate in current and previous cognitive/behavioral experiments conducted by the [Computational Cognition Lab](https://www.crumplab.com) at Brooklyn College, run by [Dr. Matthew Crump](https://www.brooklyn.edu/faculty-staff/matthew-crump/).

### Tell me more about the purpose of your research

We conduct experiments to advance knowledge about basic cognitive abilities, such as learning, memory, attention, and skilled performance (like typing on a keyboard, or playing a guitar). Any research activities that result in publications are shared on the [lab publication page](https://crumplab.com/Publications.html).

### What can I expect as participant?

Each experiment involves different tasks and tests unique hypotheses about cognitive processes. In general, each experiment info page will outline the basic task and what to expect as a participant. 

Many of our experiments involve a series of trials where you will be presented with a stimulus (e.g., a word, symbol, or picture), and asked to perform some kind of response with the keyboard or a mouse. 
An individual experiment usually takes 5 - 20 minutes to complete. Estimated times are included for each experiment.

### Can I stop participating at any time?

Absolutely, simply close the webpage for the task.

### What kind of data is collected?

We use a javascript library called [jspsych](https://www.jspsych.org/7.3/) to program our experiments for web browsers. We collect data that relates to user interactions with the experiment, such as the timing and accuracy of keyboard button presses, or mouse movements that correspond to task-related behavior. 

We do not collect identifying information.

Throughout the experiment data is saved as a javascript variable on the users computer, and sent to our experiment server as a JSON object. This data file represents the trial-by-trial interactions from the experiment, including the stimuli presented at each interval, and the responses (if any) associated with each trial. Individual users are assigned a random alphanumeric key that is coded into the data file. 

### Do I get to see my results?

Good question! This will depend on the particular experiment that you participate in. Many of the experiments on the site are designed for students learning about human cognition. These experiments will often present individual results at the end of the experiment. Other experiments will not display individual results.

It's important to note that individual results from a given task may not be very meaningful. For example, human behavior is variable and our task may not provide a precise measure at the level of a single individual. However, by combining performance across many individuals it is possible to see more reliable trends.

### Is there any compensation for participating?

We are creating this website for people interested in participating on a free volunteer basis. 

We are very grateful for your participation! We hope we can return the favor by sharing our research process and findings from people like you who have helped us learn more about human cognition!

### What do we do with the data?

We submit the data to various forms of statistical analysis to understand how people performed the task. In general, our tasks employ experimental manipulations and we are most interested in how task performance changes between the experimental manipulations. 

One overarching goal is improve our theoretical understanding of basic cognitive processes. For example, theories of memory may imply that a particular pattern of performance ought to be observed in one of our experimental conditions. By conducting the experiment we can determine whether or not the pattern occurs, which in turn helps inform our theoretical understanding.

In general, a given research project involves a series of experiments where we collect performance data from people who volunteer to participate in our tasks. After data collection and analysis is complete we write up our results in the form of a research manuscript that is submitted to a peer-reviewed scientific journal for publication.

The publication process can take a while. For example, if you contributed data to an experiment as a participant today, it could take up to a year or longer for the research cycle to produce a publication from the lab that is available for you to read (e.g., on our [publication page](https://crumplab.com/Publications.html)).

We also share as much of our research as possible, including the data from our experiments. 

## Sharing our science

The lab is committed to sharing as much of our research process as possible, including data from our experiments. Below we describe a few reasons why we think sharing is important and  what we do and don't share.

### Why do we share our work?

The Computational Cognition lab is run by Dr. Matthew Crump at Brooklyn College of CUNY. CUNY is a public institution, and research funding is almost always obtained through tax-payer funded institutions (e.g., NSF, or internal CUNY grants). As a result, it is important to the lab that research produced through public funding is available to the public who funded it. At a minimum, we are committed to sharing the outputs of our research in the form of published manuscripts. Some of the papers we publish may be behind a paywall on the official journal website, but they are also available for free on the [lab publication page](https://crumplab.com/Publications.html).

Sharing our research process is also helpful to the scientific community. For example, if we share our methods, analyses, and data, it is possible for other researchers to double-check our findings and correct mistakes. Our materials (usually computer code for programming the experiments, or for analyzing data) may also be helpful examples for other researchers who are attempting to answer similar questions. If we share our work it is also possible for other researchers to replicate what we are doing, and they find similar results to our own, then everyone can be more confident in the findings. 

### What we share/ do not share

At a minimum we share the finished products of a research project in the form of a published manuscript. 

When we have the resources and time to share additional material we share as much as we can. For example, we would share the code we used to conduct each experiment (usually javascript), the code we used to conduct the statistical analysis (usually R), and the de-identified (anonymous) raw data files from each participant in the experiment.

We typically collect generic demographic information from each participant. Individual participants are assigned a random alphanumeric code when they complete an experiment, and this code is embedded into the data file. This process is anonymous even to us, because we don't know who completes our experiments or what random code they will be assigned.

We do not collect identifying information such as your name.

When we share our research process we typically bundle all of the assets from research project together and upload them to an online repository, like the open science framework, or github. This allows other interested researchers to obtain our materials and use them to aid their research process. 

## Contact

If you have further questions please contact Dr. Matthew Crump at mcrump@brooklyn.cuny.edu.

